yungyuc/nsdhw_23au

- hw0/lolainta/countline.py
> HW0 LolaInTa

- hw0/yuanhenglee/countline.py
> HW0 yuanhenglee

- hw0/ShangHungWan/countline.py
> hw0 submitted by ShangHungWan

- hw0/yxuan0329/countline.py
> hw0 submitted by yxuan0329

- hw0/alan910127/countline.py
> hw0 submit by alan910127

- hw0/adcf3016/countline.py
> adcf3016 hw0 attempt1

- hw0/tsaiet/countline.py
> Tsaiet hw0 attempt2

- hw0/Yvonne-ul6u45p/countline.py
> Yvonne-ul6u45p hw0 attempt1

- hw1/alan910127/countline.py
- hw1/alan910127/countline.sh
> alan910127 HW1 attempt1

- hw1/Sheng08/countline.py
- hw1/Sheng08/countline.sh
> Sheng08 hw1 attempt1

- hw1/Alkalid/countline.py
- hw1/Alkalid/countline.sh
> Alkalid hw1 attempt1

- hw1/yxuan0329/countline.py
- hw1/yxuan0329/countline.sh
> hw1 attempt1 submitted by yxuan0329

- hw1/yuanhenglee/countline.py
- hw1/yuanhenglee/countline.sh
> Yuanhenglee hw1 attempt1

- hw1/oooJiun/countline.py
- hw1/oooJiun/countline.sh
> oooJiun hw1 attempt1

- hw1/Yu-Rou-Weng/countline.py
- hw1/Yu-Rou-Weng/countline.sh
> Yu-Rou-Weng hw1 attempt1

- hw1/threemonth03/countline.py
- hw1/threemonth03/countline.sh
> First submission of hw1

- hw1/visitorckw/countline.py
- hw1/visitorckw/countline.sh
> visitorckw hw1 attempt1

- hw1/Mibudin/countline.py
- hw1/Mibudin/countline.sh
> hw1 submit by Mibudin

- hw1/Yvonne-ul6u45p/countline.py
- hw1/Yvonne-ul6u45p/countline.sh
> Yvonne-ul6u45p hw1 attempt1

- hw1/CodeStone1125/countline.py
- hw1/CodeStone1125/countline.sh
> hw1 submit by CodeStone1125 attempt2

- hw1/adcf3016/countline.py
- hw1/adcf3016/countline.sh
> adcf3016 hw1 attempt1

- hw1/yui0303/countline.py
- hw1/yui0303/countline.sh
>  yui0303 hw1 attempt2

- hw1/pete0707/countline.py
- hw1/pete0707/countline.sh
> pete0707 hw1 attempt1

- hw1/oooJiun/countline.py
- hw1/oooJiun/countline.sh
> oooJiun hw1 attempt2

- hw2/alan910127/.clang-format
- hw2/alan910127/q1/Makefile
- hw2/alan910127/q1/src/line.cpp
- hw2/alan910127/q1/src/line.hpp
- hw2/alan910127/q1/src/main.cpp
- hw2/alan910127/q2/.gitignore
- hw2/alan910127/q2/Makefile
- hw2/alan910127/q2/requirements.txt
- hw2/alan910127/q2/src/_vector.cpp
- hw2/alan910127/q2/tests/test_vector.py
> alan910127 hw2 attempt1

- hw2/liamlin5566/q1/Line.cpp
- hw2/liamlin5566/q1/Line.hpp
- hw2/liamlin5566/q1/main.cpp
- hw2/liamlin5566/q1/makefile
- hw2/liamlin5566/q2/makefile
- hw2/liamlin5566/q2/test_angle.py
- hw2/liamlin5566/q2/utils.cpp
> add q1 and q2 for liamlin5566-hw2-attempt2

- hw2/Sheng08/q1/Line.cpp
- hw2/Sheng08/q1/Line.hpp
- hw2/Sheng08/q1/Makefile
- hw2/Sheng08/q1/main.cpp
- hw2/Sheng08/q2/Makefile
- hw2/Sheng08/q2/_vector.cpp
- hw2/Sheng08/q2/test_vector_angle.py
> Sheng08 hw2 attempt1

- hw2/Alkalid/q1/line.cpp
- hw2/Alkalid/q1/line.h
- hw2/Alkalid/q1/main.cpp
- hw2/Alkalid/q1/makefile
- hw2/Alkalid/q2/angle.cpp
- hw2/Alkalid/q2/makefile
- hw2/Alkalid/q2/test_vector.py
> Alkalid-hw2-attempt1

- hw2/oooJiun/q1/Line.cpp
- hw2/oooJiun/q1/Line.hpp
- hw2/oooJiun/q1/Makefile
- hw2/oooJiun/q2/Makefile
- hw2/oooJiun/q2/_vector.cpp
- hw2/oooJiun/q2/test_angle.py
> oooJiun hw2 attempt1

- hw2/Yu-Rou-Weng/q1/line.cpp
- hw2/Yu-Rou-Weng/q1/makefile
- hw2/Yu-Rou-Weng/q2/cal_angle.cpp
- hw2/Yu-Rou-Weng/q2/makefile
- hw2/Yu-Rou-Weng/q2/test_cal_angle.py
> Yu-Rou-Weng-hw2-attempt2

- hw2/visitorckw/q1/Line.cpp
- hw2/visitorckw/q1/Line.h
- hw2/visitorckw/q1/Makefile
- hw2/visitorckw/q1/main.cpp
- hw2/visitorckw/q2/Makefile
- hw2/visitorckw/q2/main.cpp
- hw2/visitorckw/q2/test_angle.py
> visitorckw hw2 attempt1

- hw2/Yvonne-ul6u45p/q1/Line.cpp
- hw2/Yvonne-ul6u45p/q1/Line.hpp
- hw2/Yvonne-ul6u45p/q1/Makefile
- hw2/Yvonne-ul6u45p/q2/Makefile
- hw2/Yvonne-ul6u45p/q2/calculateAngle.cpp
- hw2/Yvonne-ul6u45p/q2/test_calculateAngle.py
> Yvonne-ul6u45p-hw2-attempt2

- project/README.rst
- project/visitorckw/README.md
> visitorckw proposal: Runtime Profile-Guided Optimization Sorting Library

- hw3/Sheng08/Makefile
- hw3/Sheng08/_matrix.cpp
- hw3/Sheng08/_matrix.h
- hw3/Sheng08/performance.txt
- hw3/Sheng08/test_matrix.py
> Sheng08 hw3 attempt1

- hw3/liamlin5566/Matrix.cpp
- hw3/liamlin5566/Matrix.h
- hw3/liamlin5566/benchmark.py
- hw3/liamlin5566/makefile
- hw3/liamlin5566/performance.txt
- hw3/liamlin5566/test_matrix.py
> Liamlin5566 hw3 attempt1

- hw3/Alkalid/Makefile
- hw3/Alkalid/_matrix.cpp
- hw3/Alkalid/performance.txt
- hw3/Alkalid/test_matrix.py
> Alkalid hw3 attempt1

- hw3/oooJiun/Makefile
- hw3/oooJiun/_matrix.cpp
- hw3/oooJiun/performance.py
- hw3/oooJiun/performance.txt
- hw3/oooJiun/test_matrix.py
> oooJiun hw3 attempt1

- hw3/ShangHungWan/.gitignore
- hw3/ShangHungWan/Makefile
- hw3/ShangHungWan/benchmark.py
- hw3/ShangHungWan/main.cpp
- hw3/ShangHungWan/performance.txt
- hw3/ShangHungWan/test__matrix.py
> ShangHungWan hw3 attempt1

- hw3/Yu-Rou-Weng/_matrix.cpp
- hw3/Yu-Rou-Weng/makefile
- hw3/Yu-Rou-Weng/performance.py
- hw3/Yu-Rou-Weng/performance.txt
- hw3/Yu-Rou-Weng/test_matrix.py
> Yu-Rou-Weng hw3 attempt3

- hw3/ThreeMonth03/Makefile
- hw3/ThreeMonth03/_matrix.cpp
- hw3/ThreeMonth03/_matrix.hpp
- hw3/ThreeMonth03/performance.txt
- hw3/ThreeMonth03/test_matrix.py
> Three month03 hw3 attempt3

- hw3/ThreeMonth03/Makefile
- hw3/ThreeMonth03/_matrix.cpp
- hw3/ThreeMonth03/performance.txt
- hw3/ThreeMonth03/test_matrix.py
> Finish hw3

- hw3/ThreeMonth03/Makefile
- hw3/ThreeMonth03/_matrix.cpp
- hw3/ThreeMonth03/performance.txt
- hw3/ThreeMonth03/test_matrix.py
> Three month03 hw3 attempt2

- hw3/Mibudin/Makefile
- hw3/Mibudin/_matrix.cpp
- hw3/Mibudin/_matrix.hpp
- hw3/Mibudin/matrix.cpp
- hw3/Mibudin/matrix.hpp
- hw3/Mibudin/performance.py
- hw3/Mibudin/performance.txt
- hw3/Mibudin/test_matrix.py
> hw3 submit by Mibudin

- hw3/adcf3016/Makefile
- hw3/adcf3016/_matrix.cpp
- hw3/adcf3016/performance.py
- hw3/adcf3016/performance.txt
- hw3/adcf3016/test_matrix.py
> adcf3016 hw3 attempt1

- hw3/yui0303/.gitignore
- hw3/yui0303/Makefile
- hw3/yui0303/_matrix.cpp
- hw3/yui0303/_matrix.hpp
- hw3/yui0303/performance.txt
- hw3/yui0303/test_matrix.py
> yui0303 hw3 attempt1

- hw3/tsaiet/Makefile
- hw3/tsaiet/_matrix.cpp
- hw3/tsaiet/performance.py
- hw3/tsaiet/performance.txt
- hw3/tsaiet/test_matrix.py
> Tsaiet hw3 attempt3

- hw3/leeshengcian/_matrix.cc
- hw3/leeshengcian/_matrix.h
- hw3/leeshengcian/benchmark.py
- hw3/leeshengcian/makefile
- hw3/leeshengcian/test_matrix.py
> leeshengcian-hw3-attempt1

- hw4/Sheng08/Makefile
- hw4/Sheng08/_matrix.cpp
- hw4/Sheng08/_matrix.hpp
- hw4/Sheng08/myAllocator.hpp
- hw4/Sheng08/test_matrix.py
> Sheng08 hw4 attempt1

- hw4/yxuan0329/Makefile
- hw4/yxuan0329/includes/matrix.h
- hw4/yxuan0329/matrix.cpp
> yxuan0329 hw4 attempt1

- hw4/oooJiun/Makefile
- hw4/oooJiun/_matrix.cpp
> oooJiun hw4 attempt1

- hw4/ShangHungWan/.gitignore
- hw4/ShangHungWan/ByteCounter.cpp
- hw4/ShangHungWan/Makefile
- hw4/ShangHungWan/includes/ByteCounter.h
- hw4/ShangHungWan/main.cpp
- hw4/ShangHungWan/test__matrix.py
- hw4/ShangHungWan/validate.py
> ShangHungWan hw4 attempt1

- hw4/Yu-Rou-Weng/Makefile
- hw4/Yu-Rou-Weng/_matrix.cpp
- hw4/Yu-Rou-Weng/_matrix.hpp
- hw4/Yu-Rou-Weng/test_matrix.py
> Yu-Rou-Weng-hw4-attempt4

- hw4/visitorckw/.clang-format
- hw4/visitorckw/Makefile
- hw4/visitorckw/matrix.cpp
- hw4/visitorckw/test_matrix.py
> visitorckw hw4 attempt1

- hw4/Mibudin/Makefile
- hw4/Mibudin/inc/matrix/matrix.hpp
- hw4/Mibudin/inc/matrix/stl.hpp
- hw4/Mibudin/src/_matrix.pybind11.cpp
- hw4/Mibudin/src/matrix/matrix.cpp
- hw4/Mibudin/src/matrix/stl.cpp
- hw4/Mibudin/test_matrix.py
> Mibudin hw4 attempt1

- hw4/leeshengcian/Makefile
- hw4/leeshengcian/_matrix.cpp
- hw4/leeshengcian/_matrix.h
- hw4/leeshengcian/test.py
> leeshengcian-hw4-attempt2

- hw4/Yvonne-ul6u45p/CustomAllocator.hpp
- hw4/Yvonne-ul6u45p/Makefile
- hw4/Yvonne-ul6u45p/_matrix.cpp
- hw4/Yvonne-ul6u45p/test_matrix.py
> Yvonne-ul6u45p-hw4-attempt1

- hw4/adcf3016/Makefile
- hw4/adcf3016/_matrix.cpp
- hw4/adcf3016/allocator.h
> adcf3016 hw4 attempt1

- hw4/yui0303/Makefile
- hw4/yui0303/_allocator.hpp
- hw4/yui0303/_matrix.cpp
- hw4/yui0303/_matrix.hpp
- hw4/yui0303/pybind.cpp
- hw4/yui0303/test_matrix.py
> yui0303 hw4 attempt2

- hw3/Yvonne-ul6u45p/Makefile
- hw3/Yvonne-ul6u45p/benchmark.py
- hw3/Yvonne-ul6u45p/matrixMultiply.cpp
- hw3/Yvonne-ul6u45p/performance.txt
- hw3/Yvonne-ul6u45p/test_matrixMultiply.py
> Yvonne-ul6u45p-hw3-attempt2
